services: 
  kuma:
    image: louislam/uptime-kuma:1.23.16
    container_name: kuma
    restart: always
    ports:
      - 3001:3001
    environment:
      UPTIME_KUMA_ADMIN_EMAIL: admin@example.com
      UPTIME_KUMA_ADMIN_PASSWORD: admin123
      UPTIME_KUMA_BASIC_AUTH_USERNAME: admin96
      UPTIME_KUMA_BASIC_AUTH_PASSWORD: admin123
      UPTIME_KUMA_PROMETHEUS_URL: http://prometheus:9090/api/v1/query
      UPTIMEKUMA_GRAFANA_ENABLE: true
      UPTIMEKUMA_GRAFANA_URL: http://grafana:3000
    volumes:
      - ./uptime-kuma:/app/data
    networks:
      connet:
        ipv4_address: 192.168.22.10
    depends_on:
      - prometheus
  prometheus:
    image: prom/prometheus:v2.51.1
    container_name: prometheus
    restart: unless-stopped
    ports:
      - 9090:9090
    networks:
      connet:
        ipv4_address: 192.168.22.11
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus/data
      - ./config/alertmanager.yml:/etc/prometheus/alertmanager.yml
      - ./config/alert_rules.yml:/etc/prometheus/alert_rules.yml
    user: "root:root"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
  alertmanager:
    image: prom/alertmanager:v0.27.0
    container_name: alertmanager
    volumes:
      - ./config/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
    ports:
      - 9093:9093
    networks:
      connet:
        ipv4_address: 192.168.22.14

  alert-producer: 
    image: alert-producer:v1
    container_name: alert-producer
    build:  
      context: .
      dockerfile: Dockerfile
    ports:
      - 8435:8435
    restart: unless-stopped
    environment:
      - GOTIFY_URL=http://GOTIFY_URL/
      - GOTIFY_DEFAULT_PRIORITY=5
      - GOTIFY_TOKEN=test 
      - PORT=8435
    networks:
      connet:
        ipv4_address: 192.168.22.15

  grafana:
    image: grafana/grafana:10.1.9
    container_name: grafana
    restart: unless-stopped
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    networks:
     connet:
       ipv4_address: 192.168.22.12
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./config/grafana:/etc/grafana/provisioning/
      - grafana_data:/var/lib/grafana
    
networks:
  connet:
    external: true
volumes:
  grafana_data:
  prometheus_data: